#Insertion Sort 

'''
- Used for sorting.
- Works on shifting elements rather then swapping.

How it works ?
- Divide list into two parts sorted and unsorted.
- Element fetches from the Unsorted list and then in sorted list it will compare with all.

Example :

 - 7 2 91 77 3
 
 - step 1 : 7 | 2 91 77 3
 - step 2 : 2 7 | 91 77 3
 - step 3 : 2 7 91 | 77 3
 - step 4 : 2 7 77 91 | 3
 - step 5 : 2 3 7 77 91   // DONE.

 THANK YOU.
'''


def insertion_sort(data):
	n = len(data)
	for i in range(n):
		index = i
		value = data[i]
		while data[index] < data[index-1] and index > 0:
			#print("index : " ,index)
			data[index] = data[index-1]
			data[index-1] = value
			#print(f"DATA[index-1] : { data[index-1] } DATA[index] : { data[index] } " )
			index -= 1
			
		data[index] = value
	
	return data;
			
			
				
			

if __name__ == "__main__":
	data = []
	size = int(input("How many data you want to enter ? : "))
	
	print("\n-----------------INITIALISING----------------")
	for i in range(size):
		temp = int(input(f"Enter element { i + 1 } : "))
		data.append(temp)
		
	print("\n-----------------BEFORE SORTING DATA----------")
	print(data)
	
	print("\n-----------------AFTER SORTING DATA-----------")
	print(insertion_sort(data))
	
#Generated by Niteshkumar Prajapati.